# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a8064cf33159ce6aac988a496cd799b0"
name = "webp-converter"
application_url = "https://webp-converter-1hz3.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_files,write_metaobjects,write_metaobject_definitions"

[auth]
redirect_urls = [
  "https://webp-converter-1hz3.onrender.com/auth/callback"
]
